import { makePreviewDataUrl } from "@/lib/media";

const now = new Date().toISOString();

export const seedData = {
  User: [
    {
      id: "user-admin-1",
      full_name: "Surafel Mengistu",
      email: "admin@fleetops.local",
      role: "admin",
      created_date: "2026-05-01T08:00:00.000Z",
    },
    {
      id: "user-driver-1",
      full_name: "Dawit Bekele",
      email: "driver@fleetops.local",
      role: "driver",
      driver_id: "drv-001",
      created_date: "2026-05-01T08:05:00.000Z",
    },
    {
      id: "user-dispatcher-1",
      full_name: "Mekdes Tadesse",
      email: "dispatcher@fleetops.local",
      role: "dispatcher",
      created_date: "2026-05-01T08:10:00.000Z",
    },
    {
      id: "user-main-mech-1",
      full_name: "Abebe Kebede",
      email: "main.mechanic@fleetops.local",
      role: "main_mechanic",
      created_date: "2026-05-01T08:15:00.000Z",
    },
    {
      id: "user-sub-mech-1",
      full_name: "Lina Tesfaye",
      email: "sub.mechanic@fleetops.local",
      role: "main_mechanic",
      created_date: "2026-05-01T08:20:00.000Z",
    },
  ],

  Vehicle: [
    {
      id: "veh-001",
      plate_number: "AA-12034",
      make: "Volvo",
      model: "FH16",
      year: 2021,
      vehicle_type: "truck",
      current_mileage: 128400,
      status: "active",
      fuel_level: "3/4",
      notes: "Addis Ababa city and short-haul routes",
      created_date: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "veh-002",
      plate_number: "AA-22451",
      make: "Scania",
      model: "R500",
      year: 2022,
      vehicle_type: "truck",
      current_mileage: 78210,
      status: "active",
      fuel_level: "full",
      notes: "Supervisor and logistics coordination vehicle",
      created_date: "2026-05-02T09:00:00.000Z",
    },
    {
      id: "veh-003",
      plate_number: "AA-31987",
      make: "MAN",
      model: "TGX 18.510",
      year: 2020,
      vehicle_type: "truck",
      current_mileage: 166950,
      status: "in_garage",
      fuel_level: "1/4",
      notes: "Currently at Kality garage for service",
      created_date: "2026-05-03T09:00:00.000Z",
    },
    {
      id: "veh-004",
      plate_number: "AA-45231",
      make: "Mercedes-Benz",
      model: "Actros 2651",
      year: 2020,
      vehicle_type: "truck",
      current_mileage: 312450,
      status: "active",
      fuel_level: "3/4",
      notes: "Long-haul Addis Ababaâ€“Jimmaâ€“Gambella route",
      created_date: "2026-01-10T08:00:00.000Z",
    },
    {
      id: "veh-005",
      plate_number: "AA-67894",
      make: "Volvo",
      model: "FMX 500",
      year: 2019,
      vehicle_type: "truck",
      current_mileage: 487200,
      status: "active",
      fuel_level: "1/2",
      notes: "Addis Ababaâ€“Djibouti corridor primary hauler",
      created_date: "2026-01-12T08:00:00.000Z",
    },
    {
      id: "veh-006",
      plate_number: "OR-11432",
      make: "DAF",
      model: "XF 530",
      year: 2021,
      vehicle_type: "truck",
      current_mileage: 198600,
      status: "active",
      fuel_level: "full",
      notes: "Based in Adama, serves eastern corridor",
      created_date: "2026-02-01T08:00:00.000Z",
    },
    {
      id: "veh-007",
      plate_number: "AA-78341",
      make: "Kenworth",
      model: "T680",
      year: 2022,
      vehicle_type: "truck",
      current_mileage: 143800,
      status: "in_garage",
      fuel_level: "1/4",
      notes: "Currently at Kality garage for full service",
      created_date: "2026-02-15T08:00:00.000Z",
    },
    {
      id: "veh-008",
      plate_number: "AA-53672",
      make: "Mack",
      model: "Anthem 64T",
      year: 2020,
      vehicle_type: "truck",
      current_mileage: 394100,
      status: "active",
      fuel_level: "3/4",
      notes: "Addis Ababaâ€“Bahir Darâ€“Gondar northern corridor",
      created_date: "2026-01-20T08:00:00.000Z",
    },
    {
      id: "veh-009",
      plate_number: "AA-29874",
      make: "Freightliner",
      model: "Cascadia",
      year: 2023,
      vehicle_type: "truck",
      current_mileage: 54300,
      status: "active",
      fuel_level: "full",
      notes: "Supervisor field vehicle",
      created_date: "2026-03-01T08:00:00.000Z",
    },
    {
      id: "veh-010",
      plate_number: "HR-20341",
      make: "Peterbilt",
      model: "579",
      year: 2021,
      vehicle_type: "truck",
      current_mileage: 221750,
      status: "active",
      fuel_level: "1/2",
      notes: "Hawassaâ€“Shashemeneâ€“Dilla regional route",
      created_date: "2026-02-10T08:00:00.000Z",
    },
  ],

  Driver: [
    {
      id: "drv-001",
      name: "Dawit Bekele",
      license_number: "ET-DL-88231",
      phone: "+251 911 100 001",
      assigned_vehicle_id: "veh-001",
      status: "active",
      notes: "Addis Ababa short-haul and city routes",
      created_date: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "drv-002",
      name: "Selam Haile",
      license_number: "ET-DL-99218",
      phone: "+251 911 100 002",
      assigned_vehicle_id: "veh-002",
      status: "active",
      notes: "Coordination and supervisor support driver",
      created_date: "2026-05-02T10:00:00.000Z",
    },
    {
      id: "drv-003",
      name: "Abel Girma",
      license_number: "ET-DL-77290",
      phone: "+251 911 100 003",
      assigned_vehicle_id: "veh-003",
      status: "active",
      notes: "Van delivery routes, currently on standby",
      created_date: "2026-05-03T10:00:00.000Z",
    },
    {
      id: "drv-004",
      name: "Tadesse Woldemichael",
      license_number: "ET-DL-44312",
      phone: "+251 911 234 567",
      assigned_vehicle_id: "veh-004",
      status: "active",
      notes: "10 years long-haul experience, Jimma route specialist",
      created_date: "2026-01-10T10:00:00.000Z",
    },
    {
      id: "drv-005",
      name: "Bekele Girma",
      license_number: "ET-DL-55821",
      phone: "+251 912 345 678",
      assigned_vehicle_id: "veh-005",
      status: "on_trip",
      notes: "Djibouti corridor driver, valid transit permit",
      created_date: "2026-01-12T10:00:00.000Z",
    },
    {
      id: "drv-006",
      name: "Mulugeta Assefa",
      license_number: "ET-DL-61023",
      phone: "+251 913 456 789",
      assigned_vehicle_id: "veh-006",
      status: "active",
      notes: "Eastern corridor, Adamaâ€“Dire Dawa",
      created_date: "2026-02-01T10:00:00.000Z",
    },
    {
      id: "drv-007",
      name: "Yohannes Tesfaye",
      license_number: "ET-DL-70234",
      phone: "+251 914 567 890",
      assigned_vehicle_id: "veh-007",
      status: "active",
      notes: "Currently on standby while vehicle is in garage",
      created_date: "2026-02-15T10:00:00.000Z",
    },
    {
      id: "drv-008",
      name: "Girma Hailu",
      license_number: "ET-DL-83410",
      phone: "+251 915 678 901",
      assigned_vehicle_id: "veh-008",
      status: "on_trip",
      notes: "Northern corridor specialist, Bahir Dar and Gondar routes",
      created_date: "2026-01-20T10:00:00.000Z",
    },
    {
      id: "drv-009",
      name: "Tigist Alemu",
      license_number: "ET-DL-91204",
      phone: "+251 916 789 012",
      assigned_vehicle_id: "veh-010",
      status: "active",
      notes: "Southern regional routes, Hawassa area",
      created_date: "2026-02-10T10:00:00.000Z",
    },
  ],

  Trip: [
    {
      id: "trip-001",
      vehicle_id: "veh-001",
      driver_id: "drv-001",
      driver_name: "Dawit Bekele",
      origin: "Addis Ababa",
      destination: "Adama",
      departure_datetime: "2026-05-24T07:30",
      cargo_description: "Packaged consumer goods",
      load_weight: "4.8 tons",
      load_notes:
        "Loaded at Kality industrial zone. Deliver to Adama distribution center.",
      dispatcher_notes: "Call warehouse on arrival. Return same day.",
      status: "departed",
      has_vehicle_warnings: true,
      departed_at: "2026-05-24T07:45:00.000Z",
      created_date: "2026-05-24T06:45:00.000Z",
    },
    {
      id: "trip-002",
      vehicle_id: "veh-002",
      driver_id: "drv-002",
      driver_name: "Selam Haile",
      origin: "Addis Ababa",
      destination: "Hawassa",
      departure_datetime: "2026-05-25T09:00",
      cargo_description: "Office supplies and documents",
      load_weight: "0.8 tons",
      dispatcher_notes:
        "Pick up signed contracts from Hawassa regional office.",
      status: "confirmed",
      has_vehicle_warnings: false,
      created_date: "2026-05-24T08:10:00.000Z",
    },
    {
      id: "trip-003",
      vehicle_id: "veh-003",
      driver_id: "drv-003",
      driver_name: "Abel Girma",
      origin: "Addis Ababa",
      destination: "Mojo",
      departure_datetime: "2026-05-20T05:30",
      cargo_description: "Packaging materials",
      load_weight: "2.1 tons",
      dispatcher_notes: "Return signed delivery docs.",
      status: "closed",
      has_vehicle_warnings: false,
      departed_at: "2026-05-20T05:45:00.000Z",
      arrived_at: "2026-05-20T07:40:00.000Z",
      created_date: "2026-05-20T04:55:00.000Z",
    },
    {
      id: "trip-004",
      vehicle_id: "veh-004",
      driver_id: "drv-004",
      driver_name: "Tadesse Woldemichael",
      origin: "Addis Ababa",
      destination: "Jimma",
      departure_datetime: "2026-05-22T05:00",
      cargo_description: "Cement bags and construction rebar",
      load_weight: "14.5 tons",
      load_notes:
        "Loaded at Kality industrial zone. Deliver to Jimma Construction Depot.",
      dispatcher_notes:
        "Check axle weight at Holeta weigh station. Call depot 1hr before arrival.",
      status: "closed",
      has_vehicle_warnings: false,
      departed_at: "2026-05-22T05:20:00.000Z",
      arrived_at: "2026-05-22T14:45:00.000Z",
      created_date: "2026-05-21T18:00:00.000Z",
    },
    {
      id: "trip-005",
      vehicle_id: "veh-005",
      driver_id: "drv-005",
      driver_name: "Bekele Girma",
      origin: "Addis Ababa",
      destination: "Dire Dawa",
      departure_datetime: "2026-05-23T04:30",
      cargo_description:
        "Import goods from Djibouti port â€” electronics and textiles",
      load_weight: "18.2 tons",
      load_notes:
        "Customs cleared at Djibouti. Documents in cab. Deliver to Dire Dawa bonded warehouse.",
      dispatcher_notes:
        "Fuel at Awash. Do not exceed 80km/h on mountain descent after Mieso.",
      status: "departed",
      has_vehicle_warnings: true,
      departed_at: "2026-05-23T04:55:00.000Z",
      created_date: "2026-05-22T20:00:00.000Z",
    },
    {
      id: "trip-006",
      vehicle_id: "veh-008",
      driver_id: "drv-008",
      driver_name: "Girma Hailu",
      origin: "Addis Ababa",
      destination: "Bahir Dar",
      departure_datetime: "2026-05-24T06:00",
      cargo_description: "Edible oil drums and flour sacks",
      load_weight: "16.8 tons",
      load_notes:
        "Load sealed at Shola market warehouse. Deliver to Bahir Dar food distribution center.",
      dispatcher_notes:
        "Fuel stop at Dejen. Report arrival to dispatch immediately.",
      status: "departed",
      has_vehicle_warnings: false,
      departed_at: "2026-05-24T06:25:00.000Z",
      created_date: "2026-05-23T17:00:00.000Z",
    },
    {
      id: "trip-007",
      vehicle_id: "veh-006",
      driver_id: "drv-006",
      driver_name: "Mulugeta Assefa",
      origin: "Adama",
      destination: "Dire Dawa",
      departure_datetime: "2026-05-25T05:30",
      cargo_description: "Agricultural produce â€” teff and maize",
      load_weight: "12.0 tons",
      load_notes:
        "Loaded at Adama grain storage. Deliver to Dire Dawa market cooperative.",
      dispatcher_notes:
        "Weigh station check at Asbe Teferi. Avoid night driving after Harar.",
      status: "confirmed",
      has_vehicle_warnings: false,
      created_date: "2026-05-24T09:00:00.000Z",
    },
    {
      id: "trip-008",
      vehicle_id: "veh-010",
      driver_id: "drv-009",
      driver_name: "Tigist Alemu",
      origin: "Hawassa",
      destination: "Shashemene",
      departure_datetime: "2026-05-24T08:00",
      cargo_description: "Fish and packaged food from Hawassa lake suppliers",
      load_weight: "5.4 tons",
      load_notes: "Perishable â€” deliver within 4 hours of departure.",
      dispatcher_notes: "Priority delivery. Call on arrival.",
      status: "arrived",
      has_vehicle_warnings: false,
      departed_at: "2026-05-24T08:10:00.000Z",
      arrived_at: "2026-05-24T09:50:00.000Z",
      created_date: "2026-05-24T07:30:00.000Z",
    },
    {
      id: "trip-009",
      vehicle_id: "veh-004",
      driver_id: "drv-004",
      driver_name: "Tadesse Woldemichael",
      origin: "Jimma",
      destination: "Addis Ababa",
      departure_datetime: "2026-05-26T05:00",
      cargo_description: "Coffee sacks â€” Jimma cooperative export batch",
      load_weight: "13.2 tons",
      load_notes:
        "High-value cargo. Seal must not be broken before Kality customs.",
      dispatcher_notes:
        "Return trip after trip-004. Depart after vehicle rest day.",
      status: "confirmed",
      has_vehicle_warnings: false,
      created_date: "2026-05-23T12:00:00.000Z",
    },
    {
      id: "trip-010",
      vehicle_id: "veh-005",
      driver_id: "drv-005",
      driver_name: "Bekele Girma",
      origin: "Addis Ababa",
      destination: "Mekelle",
      departure_datetime: "2026-05-10T04:00",
      cargo_description: "Relief food aid â€” WFP consignment",
      load_weight: "20.0 tons",
      load_notes:
        "UN markings on cargo. Coordinate with escort through Dessie.",
      dispatcher_notes:
        "Overnight stop at Dessie regional depot. Coordinate with regional office.",
      status: "closed",
      has_vehicle_warnings: false,
      departed_at: "2026-05-10T04:30:00.000Z",
      arrived_at: "2026-05-11T16:00:00.000Z",
      created_date: "2026-05-09T15:00:00.000Z",
    },
  ],

  TripIssue: [
    {
      id: "issue-001",
      trip_id: "trip-001",
      vehicle_id: "veh-001",
      driver_id: "drv-001",
      driver_name: "Dawit Bekele",
      title: "Late fuel stop",
      details: "Fuel stop took longer than planned at Dukem.",
      status: "open",
      notes: [
        {
          id: "issue-note-001",
          text: "Need to check the fuel card next time.",
          author_name: "Dawit Bekele",
          author_role: "driver",
          created_date: "2026-05-24T09:15:00.000Z",
        },
      ],
      created_date: "2026-05-24T09:00:00.000Z",
      updated_date: "2026-05-24T09:15:00.000Z",
    },
    {
      id: "issue-002",
      trip_id: "trip-005",
      vehicle_id: "veh-005",
      driver_id: "drv-005",
      driver_name: "Bekele Girma",
      title: "Roadside tire change",
      details: "Front-right tire blew out on the mountain road.",
      status: "closed",
      notes: [
        {
          id: "issue-note-002",
          text: "Roadside fix was done with the spare tire.",
          author_name: "Bekele Girma",
          author_role: "driver",
          created_date: "2026-05-23T12:20:00.000Z",
        },
      ],
      created_date: "2026-05-23T11:35:00.000Z",
      updated_date: "2026-05-23T12:20:00.000Z",
    },
  ],

  MileageReport: [
    {
      id: "mileage-001",
      driver_id: "drv-001",
      driver_name: "Dawit Bekele",
      vehicle_id: "veh-001",
      period_type: "daily",
      start_date: "2026-05-24",
      end_date: "2026-05-24",
      km_traveled: 285,
      notes: "Addis Ababa to Adama and back.",
      created_date: "2026-05-24T18:00:00.000Z",
    },
    {
      id: "mileage-002",
      driver_id: "drv-001",
      driver_name: "Dawit Bekele",
      vehicle_id: "veh-001",
      period_type: "weekly",
      start_date: "2026-05-19",
      end_date: "2026-05-25",
      km_traveled: 1180,
      notes: "Week of short-haul and city work.",
      created_date: "2026-05-25T18:00:00.000Z",
    },
  ],

  TripStop: [
    {
      id: "stop-001",
      trip_id: "trip-001",
      location: "Dukem",
      stop_time: "2026-05-24T08:30",
      reason: "fuel_stop",
      notes: "Quick refuel at Total station Dukem before Adama.",
      is_part_change: false,
      logged_by: "admin",
      created_date: "2026-05-24T08:35:00.000Z",
    },
    {
      id: "stop-002",
      trip_id: "trip-004",
      location: "Holeta",
      stop_time: "2026-05-22T06:10",
      reason: "other",
      notes: "Axle weight check at Holeta weigh station. Passed.",
      is_part_change: false,
      logged_by: "admin",
      created_date: "2026-05-22T06:15:00.000Z",
    },
    {
      id: "stop-003",
      trip_id: "trip-004",
      location: "Woliso",
      stop_time: "2026-05-22T08:30",
      reason: "fuel_stop",
      notes: "Refueled 180L at Total station Woliso.",
      is_part_change: false,
      logged_by: "admin",
      created_date: "2026-05-22T08:35:00.000Z",
    },
    {
      id: "stop-004",
      trip_id: "trip-005",
      location: "Awash",
      stop_time: "2026-05-23T08:45",
      reason: "fuel_stop",
      notes: "Fueled 200L at Awash Arba station. Driver rested 30 mins.",
      is_part_change: false,
      logged_by: "admin",
      created_date: "2026-05-23T09:20:00.000Z",
    },
    {
      id: "stop-005",
      trip_id: "trip-005",
      location: "Mieso",
      stop_time: "2026-05-23T11:30",
      reason: "flat_tire",
      notes:
        "Front-right tire blowout on mountain descent. Tire changed roadside. Delay: 40 mins.",
      is_part_change: true,
      old_part_serial: "FR-5001",
      old_part_condition: "blown â€” sidewall rupture",
      new_part_serial: "FR-5009",
      new_part_brand: "Linglong",
      part_position: "front-right",
      logged_by: "admin",
      created_date: "2026-05-23T12:10:00.000Z",
    },
    {
      id: "stop-006",
      trip_id: "trip-006",
      location: "Dejen",
      stop_time: "2026-05-24T09:30",
      reason: "fuel_stop",
      notes:
        "Refueled 195L. Driver reported slight vibration on front-left wheel â€” monitoring.",
      is_part_change: false,
      logged_by: "admin",
      created_date: "2026-05-24T09:40:00.000Z",
    },
    {
      id: "stop-007",
      trip_id: "trip-010",
      location: "Dessie",
      stop_time: "2026-05-10T14:00",
      reason: "rest",
      notes:
        "Overnight stop at Dessie regional depot. Vehicle checked by local mechanic.",
      is_part_change: false,
      logged_by: "admin",
      created_date: "2026-05-10T14:05:00.000Z",
    },
    {
      id: "stop-008",
      trip_id: "trip-010",
      location: "Weldiya",
      stop_time: "2026-05-11T07:30",
      reason: "breakdown",
      notes:
        "Rear-right tire worn flat at km marker 612. Replaced with spare. Continued after 45 mins.",
      is_part_change: true,
      old_part_serial: "RR-5002",
      old_part_condition: "worn flat â€” tread gone",
      new_part_serial: "RR-5010",
      new_part_brand: "Triangle",
      part_position: "rear-right",
      logged_by: "admin",
      created_date: "2026-05-11T08:20:00.000Z",
    },
  ],


  ServiceSession: [
    {
      id: "session-001",
      vehicle_id: "veh-003",
      date: "2026-05-24",
      garage_name: "Kality Fleet Garage",
      odometer_at_entry: 166950,
      mechanic_name: "Lina Tesfaye",
      status: "open",
      notes:
        "Full inspection after Mojo trip. Rear left tire replaced en route â€” confirm and update records.",
      created_date: "2026-05-24T08:30:00.000Z",
    },
    {
      id: "session-002",
      vehicle_id: "veh-001",
      date: "2026-05-10",
      garage_name: "Megenagna Auto Works",
      odometer_at_entry: 127500,
      mechanic_name: "Sisay Tadesse",
      status: "closed",
      notes: "Routine service before May dispatch schedule.",
      closed_at: "2026-05-10T16:40:00.000Z",
      created_date: "2026-05-10T09:15:00.000Z",
    },
    {
      id: "session-003",
      vehicle_id: "veh-007",
      date: "2026-05-23",
      garage_name: "Kality Fleet Garage",
      odometer_at_entry: 143800,
      mechanic_name: "Abebe Kebede",
      status: "open",
      notes:
        "Full scheduled service. All four tires to be replaced. Oil, filters, brake pads.",
      created_date: "2026-05-23T08:00:00.000Z",
    },
    {
      id: "session-004",
      vehicle_id: "veh-004",
      date: "2026-05-01",
      garage_name: "Megenagna Auto Works",
      odometer_at_entry: 308000,
      mechanic_name: "Sisay Tadesse",
      status: "closed",
      notes: "Pre-trip service before May long-haul routes.",
      closed_at: "2026-05-01T17:30:00.000Z",
      created_date: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "session-005",
      vehicle_id: "veh-005",
      date: "2026-05-08",
      garage_name: "Kality Fleet Garage",
      odometer_at_entry: 484200,
      mechanic_name: "Abebe Kebede",
      status: "closed",
      notes: "Tire inspection and front axle grease before Mekelle trip.",
      closed_at: "2026-05-08T15:00:00.000Z",
      created_date: "2026-05-08T09:30:00.000Z",
    },
    {
      id: "session-006",
      vehicle_id: "veh-008",
      date: "2026-05-15",
      garage_name: "Megenagna Auto Works",
      odometer_at_entry: 391200,
      mechanic_name: "Sisay Tadesse",
      status: "closed",
      notes: "Routine 10,000km service. Oil, filter, tire rotation.",
      closed_at: "2026-05-15T16:00:00.000Z",
      created_date: "2026-05-15T08:30:00.000Z",
    },
  ],

  ServiceItem: [
    {
      id: "svc-item-001",
      session_id: "session-002",
      vehicle_id: "veh-001",
      item_name: "Brake inspection",
      action: "checked",
      notes: "Front pads still serviceable. Rear drums checked â€” ok.",
      is_part_replacement: false,
      created_date: "2026-05-10T10:00:00.000Z",
    },
    {
      id: "svc-item-002",
      session_id: "session-002",
      vehicle_id: "veh-001",
      item_name: "Air filter",
      action: "replaced",
      notes: "Clogged filter swapped during routine service.",
      is_part_replacement: true,
      old_serial: "AF-OLD-17",
      old_condition: "dirty â€” clogged",
      old_removal_reason: "reached service limit",
      new_serial: "AF-NEW-22",
      new_brand: "Donaldson",
      new_condition: "new",
      part_position: "n/a",
      created_date: "2026-05-10T11:20:00.000Z",
    },
    {
      id: "svc-item-003",
      session_id: "session-003",
      vehicle_id: "veh-007",
      item_name: "Front-left tire",
      action: "replaced",
      notes: "Tread worn below 2mm. Replaced with new Linglong 315/80R22.5.",
      is_part_replacement: true,
      old_serial: "FL-7001",
      old_condition: "worn â€” tread below limit",
      old_removal_reason: "safety â€” below minimum tread depth",
      new_serial: "FL-7009",
      new_brand: "Linglong",
      new_condition: "new",
      part_position: "front-left",
      created_date: "2026-05-23T10:00:00.000Z",
    },
    {
      id: "svc-item-004",
      session_id: "session-003",
      vehicle_id: "veh-007",
      item_name: "Front-right tire",
      action: "replaced",
      notes: "Same batch as FL. All front tires replaced together.",
      is_part_replacement: true,
      old_serial: "FR-7001",
      old_condition: "worn â€” tread below limit",
      old_removal_reason: "safety â€” below minimum tread depth",
      new_serial: "FR-7009",
      new_brand: "Linglong",
      new_condition: "new",
      part_position: "front-right",
      created_date: "2026-05-23T10:20:00.000Z",
    },
    {
      id: "svc-item-005",
      session_id: "session-003",
      vehicle_id: "veh-007",
      item_name: "Rear-left tire",
      action: "replaced",
      notes: "Uneven wear detected â€” suspected alignment issue.",
      is_part_replacement: true,
      old_serial: "RL-7001",
      old_condition: "worn â€” uneven wear pattern",
      old_removal_reason: "uneven wear, possible alignment issue",
      new_serial: "RL-7009",
      new_brand: "Triangle",
      new_condition: "new",
      part_position: "rear-left",
      created_date: "2026-05-23T10:45:00.000Z",
    },
    {
      id: "svc-item-006",
      session_id: "session-003",
      vehicle_id: "veh-007",
      item_name: "Rear-right tire",
      action: "replaced",
      notes: "Replaced as matching pair with RL.",
      is_part_replacement: true,
      old_serial: "RR-7001",
      old_condition: "worn â€” 30% tread remaining",
      old_removal_reason: "replaced as part of full axle set",
      new_serial: "RR-7009",
      new_brand: "Triangle",
      new_condition: "new",
      part_position: "rear-right",
      created_date: "2026-05-23T11:00:00.000Z",
    },
    {
      id: "svc-item-007",
      session_id: "session-003",
      vehicle_id: "veh-007",
      item_name: "Engine oil",
      action: "replaced",
      notes:
        "Drained 18L 15W-40. Replaced with Shell Rimula R4. Oil filter also replaced.",
      is_part_replacement: false,
      created_date: "2026-05-23T11:30:00.000Z",
    },
    {
      id: "svc-item-008",
      session_id: "session-003",
      vehicle_id: "veh-007",
      item_name: "Front brake pads",
      action: "replaced",
      notes:
        "Left and right front pads replaced. Rotors checked â€” within spec.",
      is_part_replacement: true,
      old_serial: "BP-7001",
      old_condition: "worn â€” 10% material remaining",
      old_removal_reason: "at minimum thickness",
      new_serial: "BP-7009",
      new_brand: "Textar",
      new_condition: "new",
      part_position: "n/a",
      created_date: "2026-05-23T13:00:00.000Z",
    },
    {
      id: "svc-item-009",
      session_id: "session-004",
      vehicle_id: "veh-004",
      item_name: "Engine oil",
      action: "replaced",
      notes: "Full oil drain and refill. 20L 15W-40 Mobil Delvac.",
      is_part_replacement: false,
      created_date: "2026-05-01T10:00:00.000Z",
    },
    {
      id: "svc-item-010",
      session_id: "session-004",
      vehicle_id: "veh-004",
      item_name: "Rear-left tire",
      action: "replaced",
      notes:
        "RL tire had sidewall crack. Replaced before long-haul Jimma trip.",
      is_part_replacement: true,
      old_serial: "RL-4000",
      old_condition: "cracked sidewall",
      old_removal_reason: "sidewall crack â€” unsafe for highway",
      new_serial: "RL-4001",
      new_brand: "Triangle",
      new_condition: "new",
      part_position: "rear-left",
      created_date: "2026-05-01T11:30:00.000Z",
    },
    {
      id: "svc-item-011",
      session_id: "session-004",
      vehicle_id: "veh-004",
      item_name: "Fuel filter",
      action: "replaced",
      notes:
        "Primary and secondary fuel filters replaced. Old ones dark with sediment.",
      is_part_replacement: true,
      old_serial: "FF-4001",
      old_condition: "clogged â€” heavy sediment",
      old_removal_reason: "routine replacement",
      new_serial: "FF-4009",
      new_brand: "Fleetguard",
      new_condition: "new",
      part_position: "n/a",
      created_date: "2026-05-01T13:00:00.000Z",
    },
    {
      id: "svc-item-012",
      session_id: "session-005",
      vehicle_id: "veh-005",
      item_name: "Front-right tire",
      action: "checked",
      notes:
        "FR tire showing wear at 40% remaining. Flagged for replacement on next service.",
      is_part_replacement: false,
      created_date: "2026-05-08T10:30:00.000Z",
    },
    {
      id: "svc-item-013",
      session_id: "session-005",
      vehicle_id: "veh-005",
      item_name: "Front axle grease",
      action: "adjusted",
      notes: "Front axle kingpin greased. Wheel bearing torque checked.",
      is_part_replacement: false,
      created_date: "2026-05-08T11:00:00.000Z",
    },
    {
      id: "svc-item-014",
      session_id: "session-006",
      vehicle_id: "veh-008",
      item_name: "Engine oil",
      action: "replaced",
      notes: "18L 15W-40 replaced. Oil was dark â€” due at 390,000km.",
      is_part_replacement: false,
      created_date: "2026-05-15T09:30:00.000Z",
    },
    {
      id: "svc-item-015",
      session_id: "session-006",
      vehicle_id: "veh-008",
      item_name: "Tire rotation",
      action: "adjusted",
      notes: "FR and FL rotated with RL and RR. Wear now even across all four.",
      is_part_replacement: false,
      created_date: "2026-05-15T11:00:00.000Z",
    },
    {
      id: "svc-item-016",
      session_id: "session-006",
      vehicle_id: "veh-008",
      item_name: "Air filter",
      action: "replaced",
      notes:
        "Replaced clogged air filter. Dusty roads on northern corridor accelerate clogging.",
      is_part_replacement: true,
      old_serial: "AF-8001",
      old_condition: "heavily clogged â€” dust",
      old_removal_reason: "airflow restriction",
      new_serial: "AF-8009",
      new_brand: "Donaldson",
      new_condition: "new",
      part_position: "n/a",
      created_date: "2026-05-15T12:30:00.000Z",
    },
  ],

  FinanceEntry: [
    {
      id: "finance-001",
      date: "2026-05-10",
      cost_type: "service",
      vehicle_id: "veh-001",
      session_id: "session-002",
      amount: 1450,
      notes: "Oil, filter, and brake check.",
      created_date: "2026-05-10T17:10:00.000Z",
    },
    {
      id: "finance-002",
      date: "2026-05-23",
      cost_type: "part",
      vehicle_id: "veh-007",
      session_id: "session-003",
      amount: 8400,
      notes: "Set of tires and pads.",
      created_date: "2026-05-23T16:00:00.000Z",
    },
    {
      id: "finance-003",
      date: "2026-05-08",
      cost_type: "other",
      vehicle_id: "veh-005",
      session_id: "",
      amount: 1200,
      notes: "Tow truck and road help.",
      created_date: "2026-05-08T18:30:00.000Z",
    },
  ],

  MaintenanceSchedule: [
    {
      id: "maint-001",
      vehicle_id: "veh-001",
      name: "Engine oil service",
      interval_type: "km",
      interval_value: 10000,
      last_done_mileage: 119000,
      next_due_mileage: 129000,
      status: "due_soon",
      notes: "Due at 129,000km â€” currently at 128,400km.",
      created_date: "2026-05-05T09:00:00.000Z",
    },
    {
      id: "maint-002",
      vehicle_id: "veh-003",
      name: "Rear tire replacement",
      interval_type: "time",
      interval_value: 6,
      interval_unit: "months",
      last_done_date: "2025-10-01",
      next_due_date: "2026-04-01",
      status: "overdue",
      notes: "Overdue by 7 weeks.",
      created_date: "2026-04-01T08:00:00.000Z",
    },
    {
      id: "maint-003",
      vehicle_id: "veh-004",
      name: "Engine oil service",
      interval_type: "km",
      interval_value: 10000,
      last_done_mileage: 308000,
      next_due_mileage: 318000,
      status: "ok",
      notes: "Done at Megenagna session-004.",
      created_date: "2026-05-01T17:30:00.000Z",
    },
    {
      id: "maint-004",
      vehicle_id: "veh-004",
      name: "Tire inspection â€” all four",
      interval_type: "km",
      interval_value: 20000,
      last_done_mileage: 308000,
      next_due_mileage: 328000,
      status: "ok",
      created_date: "2026-05-01T17:30:00.000Z",
    },
    {
      id: "maint-005",
      vehicle_id: "veh-004",
      name: "Fuel filter replacement",
      interval_type: "km",
      interval_value: 30000,
      last_done_mileage: 308000,
      next_due_mileage: 338000,
      status: "ok",
      created_date: "2026-05-01T17:30:00.000Z",
    },
    {
      id: "maint-006",
      vehicle_id: "veh-005",
      name: "Engine oil service",
      interval_type: "km",
      interval_value: 10000,
      last_done_mileage: 480000,
      next_due_mileage: 490000,
      status: "overdue",
      notes: "Due at 490,000km â€” currently at 487,200km and on active trip.",
      created_date: "2026-04-20T09:00:00.000Z",
    },
    {
      id: "maint-007",
      vehicle_id: "veh-005",
      name: "Front tire replacement",
      interval_type: "km",
      interval_value: 60000,
      last_done_mileage: 430000,
      next_due_mileage: 490000,
      status: "overdue",
      notes: "FR tire already blown and replaced en route at Mieso.",
      created_date: "2026-04-01T09:00:00.000Z",
    },
    {
      id: "maint-008",
      vehicle_id: "veh-005",
      name: "Brake system inspection",
      interval_type: "time",
      interval_value: 3,
      interval_unit: "months",
      last_done_date: "2026-01-15",
      next_due_date: "2026-04-15",
      status: "overdue",
      notes:
        "Overdue by 5 weeks. Vehicle currently on active trip to Dire Dawa.",
      created_date: "2026-04-15T09:00:00.000Z",
    },
    {
      id: "maint-009",
      vehicle_id: "veh-006",
      name: "Engine oil service",
      interval_type: "km",
      interval_value: 10000,
      last_done_mileage: 190000,
      next_due_mileage: 200000,
      status: "due_soon",
      notes: "Currently at 198,600km. Due in 1,400km.",
      created_date: "2026-05-10T09:00:00.000Z",
    },
    {
      id: "maint-010",
      vehicle_id: "veh-006",
      name: "Tire rotation",
      interval_type: "km",
      interval_value: 20000,
      last_done_mileage: 180000,
      next_due_mileage: 200000,
      status: "due_soon",
      created_date: "2026-05-10T09:00:00.000Z",
    },
    {
      id: "maint-011",
      vehicle_id: "veh-007",
      name: "Full tire replacement â€” all four",
      interval_type: "km",
      interval_value: 80000,
      last_done_mileage: 60000,
      next_due_mileage: 140000,
      status: "overdue",
      notes: "At 143,800km â€” overdue. Currently being replaced in session-003.",
      created_date: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "maint-012",
      vehicle_id: "veh-007",
      name: "Engine oil service",
      interval_type: "km",
      interval_value: 10000,
      last_done_mileage: 133000,
      next_due_mileage: 143000,
      status: "overdue",
      notes: "Overdue â€” being serviced now in session-003.",
      created_date: "2026-05-01T09:00:00.000Z",
    },
    {
      id: "maint-013",
      vehicle_id: "veh-008",
      name: "Engine oil service",
      interval_type: "km",
      interval_value: 10000,
      last_done_mileage: 391200,
      next_due_mileage: 401200,
      status: "ok",
      notes: "Done in session-006.",
      created_date: "2026-05-15T16:00:00.000Z",
    },
    {
      id: "maint-014",
      vehicle_id: "veh-008",
      name: "Rear tire replacement",
      interval_type: "km",
      interval_value: 60000,
      last_done_mileage: 340000,
      next_due_mileage: 400000,
      status: "due_soon",
      notes:
        "Due at 400,000km â€” currently at 394,100km on active trip to Bahir Dar.",
      created_date: "2026-05-15T16:00:00.000Z",
    },
    {
      id: "maint-015",
      vehicle_id: "veh-008",
      name: "Brake system inspection",
      interval_type: "time",
      interval_value: 3,
      interval_unit: "months",
      last_done_date: "2026-03-10",
      next_due_date: "2026-06-10",
      status: "ok",
      created_date: "2026-03-10T09:00:00.000Z",
    },
    {
      id: "maint-016",
      vehicle_id: "veh-010",
      name: "Engine oil service",
      interval_type: "km",
      interval_value: 10000,
      last_done_mileage: 215000,
      next_due_mileage: 225000,
      status: "due_soon",
      notes: "Currently at 221,750km. Due in 3,250km.",
      created_date: "2026-05-01T09:00:00.000Z",
    },
  ],

  VehicleComponent: [
    // veh-001 tires
    {
      id: "comp-001",
      vehicle_id: "veh-001",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-1001",
      position: "front-left",
      brand: "RoadMax",
      type_detail: "7.50R16",
      health_status: "good",
      install_date: "2026-02-14",
      is_active: true,
      created_date: "2026-02-14T07:00:00.000Z",
    },
    {
      id: "comp-002",
      vehicle_id: "veh-001",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-1001",
      position: "front-right",
      brand: "RoadMax",
      type_detail: "7.50R16",
      health_status: "good",
      install_date: "2026-02-14",
      is_active: true,
      created_date: "2026-02-14T07:05:00.000Z",
    },
    {
      id: "comp-024",
      vehicle_id: "veh-001",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-1001",
      position: "rear-left",
      brand: "RoadMax",
      type_detail: "7.50R16",
      health_status: "worn",
      install_date: "2026-01-10",
      notes: "Wear at 45% â€” monitor",
      is_active: true,
      created_date: "2026-01-10T08:00:00.000Z",
    },
    {
      id: "comp-025",
      vehicle_id: "veh-001",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-1001",
      position: "rear-right",
      brand: "RoadMax",
      type_detail: "7.50R16",
      health_status: "worn",
      install_date: "2026-01-10",
      notes: "Wear at 40% â€” schedule replacement",
      is_active: true,
      created_date: "2026-01-10T08:05:00.000Z",
    },
    // veh-003 tires
    {
      id: "comp-026",
      vehicle_id: "veh-003",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-3001",
      position: "front-left",
      brand: "Linglong",
      type_detail: "195R14C",
      health_status: "good",
      install_date: "2026-01-20",
      is_active: true,
      created_date: "2026-01-20T08:00:00.000Z",
    },
    {
      id: "comp-027",
      vehicle_id: "veh-003",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-3001",
      position: "front-right",
      brand: "Linglong",
      type_detail: "195R14C",
      health_status: "good",
      install_date: "2026-01-20",
      is_active: true,
      created_date: "2026-01-20T08:05:00.000Z",
    },
    {
      id: "comp-028",
      vehicle_id: "veh-003",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-3009",
      position: "rear-left",
      brand: "Triangle",
      type_detail: "195R14C",
      health_status: "good",
      install_date: "2026-05-20",
      notes: "Replaced en route near Mojo â€” spare fitted",
      is_active: true,
      created_date: "2026-05-20T07:00:00.000Z",
    },
    {
      id: "comp-029",
      vehicle_id: "veh-003",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-3001",
      position: "rear-right",
      brand: "Linglong",
      type_detail: "195R14C",
      health_status: "worn",
      install_date: "2026-01-20",
      notes: "Wear at 35% â€” overdue for replacement",
      is_active: true,
      created_date: "2026-01-20T08:10:00.000Z",
    },
    // veh-003 battery
    {
      id: "comp-003",
      vehicle_id: "veh-003",
      component_type: "battery",
      name: "Main Battery",
      serial_number: "BAT-3001",
      position: "n/a",
      brand: "VoltPro",
      health_status: "worn",
      install_date: "2025-11-02",
      is_active: true,
      created_date: "2025-11-02T09:00:00.000Z",
    },
    // veh-004 tires
    {
      id: "comp-004",
      vehicle_id: "veh-004",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-4001",
      position: "front-left",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-03-10",
      is_active: true,
      created_date: "2026-03-10T08:00:00.000Z",
    },
    {
      id: "comp-005",
      vehicle_id: "veh-004",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-4001",
      position: "front-right",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-03-10",
      is_active: true,
      created_date: "2026-03-10T08:05:00.000Z",
    },
    {
      id: "comp-006",
      vehicle_id: "veh-004",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-4001",
      position: "rear-left",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-05-01",
      notes: "Replaced in session-004 after sidewall crack",
      is_active: true,
      created_date: "2026-05-01T11:45:00.000Z",
    },
    {
      id: "comp-007",
      vehicle_id: "veh-004",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-4001",
      position: "rear-right",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "worn",
      install_date: "2026-01-15",
      notes: "Wear at 45% â€” flag for replacement at next service",
      is_active: true,
      created_date: "2026-01-15T08:00:00.000Z",
    },
    // veh-005 tires
    {
      id: "comp-008",
      vehicle_id: "veh-005",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-5001",
      position: "front-left",
      brand: "Linglong",
      type_detail: "315/80R22.5",
      health_status: "worn",
      install_date: "2025-12-01",
      notes: "Wear at 50% â€” approaching replacement interval",
      is_active: true,
      created_date: "2025-12-01T08:00:00.000Z",
    },
    {
      id: "comp-009",
      vehicle_id: "veh-005",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-5009",
      position: "front-right",
      brand: "Linglong",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-05-23",
      notes: "Replaced en route at Mieso after blowout â€” stop-005",
      is_active: true,
      created_date: "2026-05-23T12:00:00.000Z",
    },
    {
      id: "comp-010",
      vehicle_id: "veh-005",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-5001",
      position: "rear-left",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "worn",
      install_date: "2025-11-15",
      notes: "Wear at 35% â€” schedule replacement",
      is_active: true,
      created_date: "2025-11-15T08:00:00.000Z",
    },
    {
      id: "comp-011",
      vehicle_id: "veh-005",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-5010",
      position: "rear-right",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-05-11",
      notes: "Replaced en route at Weldiya after blowout â€” stop-008",
      is_active: true,
      created_date: "2026-05-11T08:30:00.000Z",
    },
    // veh-006 tires
    {
      id: "comp-020",
      vehicle_id: "veh-006",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-6001",
      position: "front-left",
      brand: "Triangle",
      type_detail: "295/80R22.5",
      health_status: "good",
      install_date: "2026-02-01",
      is_active: true,
      created_date: "2026-02-01T08:00:00.000Z",
    },
    {
      id: "comp-021",
      vehicle_id: "veh-006",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-6001",
      position: "front-right",
      brand: "Triangle",
      type_detail: "295/80R22.5",
      health_status: "good",
      install_date: "2026-02-01",
      is_active: true,
      created_date: "2026-02-01T08:05:00.000Z",
    },
    {
      id: "comp-022",
      vehicle_id: "veh-006",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-6001",
      position: "rear-left",
      brand: "Triangle",
      type_detail: "295/80R22.5",
      health_status: "good",
      install_date: "2026-02-01",
      is_active: true,
      created_date: "2026-02-01T08:10:00.000Z",
    },
    {
      id: "comp-023",
      vehicle_id: "veh-006",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-6001",
      position: "rear-right",
      brand: "Triangle",
      type_detail: "295/80R22.5",
      health_status: "good",
      install_date: "2026-02-01",
      is_active: true,
      created_date: "2026-02-01T08:15:00.000Z",
    },
    // veh-007 tires â€” all new from session-003
    {
      id: "comp-012",
      vehicle_id: "veh-007",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-7009",
      position: "front-left",
      brand: "Linglong",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-05-23",
      notes: "New â€” installed in session-003",
      is_active: true,
      created_date: "2026-05-23T10:10:00.000Z",
    },
    {
      id: "comp-013",
      vehicle_id: "veh-007",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-7009",
      position: "front-right",
      brand: "Linglong",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-05-23",
      notes: "New â€” installed in session-003",
      is_active: true,
      created_date: "2026-05-23T10:25:00.000Z",
    },
    {
      id: "comp-014",
      vehicle_id: "veh-007",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-7009",
      position: "rear-left",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-05-23",
      notes: "New â€” installed in session-003. Alignment check pending.",
      is_active: true,
      created_date: "2026-05-23T10:50:00.000Z",
    },
    {
      id: "comp-015",
      vehicle_id: "veh-007",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-7009",
      position: "rear-right",
      brand: "Triangle",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-05-23",
      notes: "New â€” installed in session-003",
      is_active: true,
      created_date: "2026-05-23T11:05:00.000Z",
    },
    // veh-008 tires
    {
      id: "comp-016",
      vehicle_id: "veh-008",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-8001",
      position: "front-left",
      brand: "Michelin",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-01-10",
      is_active: true,
      created_date: "2026-01-10T08:00:00.000Z",
    },
    {
      id: "comp-017",
      vehicle_id: "veh-008",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-8001",
      position: "front-right",
      brand: "Michelin",
      type_detail: "315/80R22.5",
      health_status: "good",
      install_date: "2026-01-10",
      is_active: true,
      created_date: "2026-01-10T08:05:00.000Z",
    },
    {
      id: "comp-018",
      vehicle_id: "veh-008",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-8001",
      position: "rear-left",
      brand: "Michelin",
      type_detail: "315/80R22.5",
      health_status: "worn",
      install_date: "2025-10-05",
      notes: "Wear at 40% â€” due for replacement at 400,000km",
      is_active: true,
      created_date: "2025-10-05T08:00:00.000Z",
    },
    {
      id: "comp-019",
      vehicle_id: "veh-008",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-8001",
      position: "rear-right",
      brand: "Michelin",
      type_detail: "315/80R22.5",
      health_status: "worn",
      install_date: "2025-10-05",
      notes: "Wear at 38% â€” replace alongside RL",
      is_active: true,
      created_date: "2025-10-05T08:05:00.000Z",
    },
    // veh-010 tires
    {
      id: "comp-030",
      vehicle_id: "veh-010",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FL-10001",
      position: "front-left",
      brand: "Triangle",
      type_detail: "7.50R16",
      health_status: "good",
      install_date: "2026-02-10",
      is_active: true,
      created_date: "2026-02-10T08:00:00.000Z",
    },
    {
      id: "comp-031",
      vehicle_id: "veh-010",
      component_type: "tire",
      name: "Steer Tire",
      serial_number: "FR-10001",
      position: "front-right",
      brand: "Triangle",
      type_detail: "7.50R16",
      health_status: "good",
      install_date: "2026-02-10",
      is_active: true,
      created_date: "2026-02-10T08:05:00.000Z",
    },
    {
      id: "comp-032",
      vehicle_id: "veh-010",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RL-10001",
      position: "rear-left",
      brand: "Triangle",
      type_detail: "7.50R16",
      health_status: "good",
      install_date: "2026-02-10",
      is_active: true,
      created_date: "2026-02-10T08:10:00.000Z",
    },
    {
      id: "comp-033",
      vehicle_id: "veh-010",
      component_type: "tire",
      name: "Drive Tire",
      serial_number: "RR-10001",
      position: "rear-right",
      brand: "Triangle",
      type_detail: "7.50R16",
      health_status: "good",
      install_date: "2026-02-10",
      is_active: true,
      created_date: "2026-02-10T08:15:00.000Z",
    },
  ],

  Notification: [
    {
      id: "notif-001",
      type: "maintenance",
      title: "Rear tire replacement overdue â€” AA-31987",
      message:
        "Vehicle AA-31987 rear tire replacement is overdue by 7 weeks. Vehicle is currently in garage session-001.",
      severity: "critical",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-31987",
      related_type: "MaintenanceSchedule",
      related_id: "maint-002",
      created_date: "2026-05-24T08:40:00.000Z",
    },
    {
      id: "notif-002",
      type: "dispatch",
      title: "Trip departed â€” Addis Ababa to Adama",
      message:
        "Vehicle AA-12034 departed with Dawit Bekele. 4.8 tons of packaged goods. Fuel stop expected at Dukem.",
      severity: "info",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-12034",
      related_type: "Trip",
      related_id: "trip-001",
      created_date: "2026-05-24T07:50:00.000Z",
    },
    {
      id: "notif-003",
      type: "garage",
      title: "Garage session opened â€” AA-31987",
      message:
        "Vehicle AA-31987 entered Kality Fleet Garage. Mechanic: Lina Tesfaye. Rear tire mismatch from Mojo trip to be confirmed.",
      severity: "warning",
      is_read: true,
      recipient_roles: "admin",
      vehicle_plate: "AA-31987",
      related_type: "ServiceSession",
      related_id: "session-001",
      created_date: "2026-05-24T08:35:00.000Z",
    },
    {
      id: "notif-004",
      type: "garage",
      title: "Full tire replacement started â€” AA-78341",
      message:
        "Vehicle AA-78341 entered Kality Fleet Garage. All 4 tires being replaced by mechanic Abebe Kebede.",
      severity: "warning",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-78341",
      related_type: "ServiceSession",
      related_id: "session-003",
      created_date: "2026-05-23T08:05:00.000Z",
    },
    {
      id: "notif-005",
      type: "garage",
      title: "Tire replaced en route â€” AA-67894 at Mieso",
      message:
        "FR tire FR-5001 blew out near Mieso on Addisâ€“Dire Dawa trip. Replaced roadside with FR-5009 (Linglong). Logged in stop-005.",
      severity: "critical",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-67894",
      related_type: "TripStop",
      related_id: "stop-005",
      created_date: "2026-05-23T12:15:00.000Z",
    },
    {
      id: "notif-006",
      type: "maintenance",
      title: "Engine oil overdue â€” AA-67894",
      message:
        "Vehicle AA-67894 engine oil service is overdue. Due at 490,000km â€” currently at 487,200km and on active trip to Dire Dawa.",
      severity: "critical",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-67894",
      related_type: "MaintenanceSchedule",
      related_id: "maint-006",
      created_date: "2026-05-23T05:00:00.000Z",
    },
    {
      id: "notif-007",
      type: "maintenance",
      title: "Brake inspection overdue â€” AA-67894",
      message:
        "Vehicle AA-67894 brake inspection is 5 weeks overdue. Vehicle is currently on active long-haul trip to Dire Dawa.",
      severity: "critical",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-67894",
      related_type: "MaintenanceSchedule",
      related_id: "maint-008",
      created_date: "2026-05-20T08:00:00.000Z",
    },
    {
      id: "notif-008",
      type: "dispatch",
      title: "Trip departed â€” Addis Ababa to Bahir Dar",
      message:
        "Vehicle AA-53672 departed with Girma Hailu. 16.8 tons of edible oil and flour. Fuel stop planned at Dejen.",
      severity: "info",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-53672",
      related_type: "Trip",
      related_id: "trip-006",
      created_date: "2026-05-24T06:30:00.000Z",
    },
    {
      id: "notif-009",
      type: "dispatch",
      title: "Trip departed with warnings â€” AA-67894 to Dire Dawa",
      message:
        "Vehicle AA-67894 departed with Bekele Girma carrying 18.2 tons. Vehicle has 3 active maintenance warnings â€” oil overdue, brake overdue, front tire overdue.",
      severity: "warning",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-67894",
      related_type: "Trip",
      related_id: "trip-005",
      created_date: "2026-05-23T05:00:00.000Z",
    },
    {
      id: "notif-010",
      type: "dispatch",
      title: "Trip arrived â€” Hawassa to Shashemene",
      message:
        "Vehicle HR-20341 arrived at Shashemene with Tigist Alemu. Perishable fish delivery completed on time.",
      severity: "info",
      is_read: true,
      recipient_roles: "admin",
      vehicle_plate: "HR-20341",
      related_type: "Trip",
      related_id: "trip-008",
      created_date: "2026-05-24T09:55:00.000Z",
    },
    {
      id: "notif-011",
      type: "maintenance",
      title: "Engine oil due soon â€” OR-11432",
      message:
        "Vehicle OR-11432 engine oil service due in 1,400km. Currently at 198,600km, due at 200,000km.",
      severity: "warning",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "OR-11432",
      related_type: "MaintenanceSchedule",
      related_id: "maint-009",
      created_date: "2026-05-24T07:00:00.000Z",
    },
    {
      id: "notif-012",
      type: "garage",
      title: "Tire mismatch resolved â€” AA-67894 trip-010",
      message:
        "RR tire change on the Mekelle trip was logged after the blowout at Weldiya km 612. RR-5002 was removed and RR-5010 was fitted.",
      severity: "info",
      is_read: true,
      recipient_roles: "admin",
      vehicle_plate: "AA-67894",
      related_type: "Trip",
      related_id: "trip-010",
      created_date: "2026-05-11T17:05:00.000Z",
    },
    {
      id: "notif-013",
      type: "maintenance",
      title: "Rear tire replacement due soon â€” AA-53672",
      message:
        "Vehicle AA-53672 rear tires due for replacement at 400,000km â€” currently at 394,100km and on active trip to Bahir Dar.",
      severity: "warning",
      is_read: false,
      recipient_roles: "admin",
      vehicle_plate: "AA-53672",
      related_type: "MaintenanceSchedule",
      related_id: "maint-014",
      created_date: "2026-05-24T06:00:00.000Z",
    },
    {
      id: "notif-014",
      type: "dispatch",
      title: "Trip closed â€” Addis Ababa to Jimma",
      message:
        "Vehicle AA-45231 returned from Jimma. 14.5 tons of cement were delivered. No issues were found.",
      severity: "info",
      is_read: true,
      recipient_roles: "admin",
      vehicle_plate: "AA-45231",
      related_type: "Trip",
      related_id: "trip-004",
      created_date: "2026-05-22T15:00:00.000Z",
    },
    {
      id: "notif-015",
      type: "dispatch",
      title: "Trip closed â€” Addis Ababa to Mekelle",
      message:
        "Vehicle AA-67894 completed Mekelle WFP food aid delivery. RR tire mismatch flagged and documented. Schedule immediate service.",
      severity: "warning",
      is_read: true,
      recipient_roles: "admin",
      vehicle_plate: "AA-67894",
      related_type: "Trip",
      related_id: "trip-010",
      created_date: "2026-05-11T17:10:00.000Z",
    },
  ],

  ServiceRecommendation: [
    {
      id: "rec-001",
      vehicle_id: "veh-003",
      mechanic_name: "Lina Tesfaye",
      recommendations:
        "Inspect rear axle alignment during current service window. Battery BAT-3001 is worn â€” replace before next dispatch.",
      priority: "high",
      due_date: "2026-05-26",
      status: "pending",
      created_date: "2026-05-24T09:00:00.000Z",
    },
    {
      id: "rec-002",
      vehicle_id: "veh-005",
      mechanic_name: "Abebe Kebede",
      recommendations:
        "Front-left tire FL-5001 is at 50% wear. Schedule replacement before next long-haul Djibouti trip. Brake system is 5 weeks overdue â€” do not dispatch until inspected.",
      priority: "urgent",
      due_date: "2026-05-28",
      status: "pending",
      created_date: "2026-05-08T15:00:00.000Z",
    },
    {
      id: "rec-003",
      vehicle_id: "veh-007",
      mechanic_name: "Abebe Kebede",
      recommendations:
        "Rear axle alignment suspected after uneven tire wear on RL-7001. Check alignment after new tires are fitted. Do not dispatch on long-haul until alignment confirmed.",
      priority: "high",
      due_date: "2026-05-25",
      status: "pending",
      created_date: "2026-05-23T13:30:00.000Z",
    },
    {
      id: "rec-004",
      vehicle_id: "veh-008",
      mechanic_name: "Sisay Tadesse",
      recommendations:
        "Rear tires RL-8001 and RR-8001 both under 40% tread. Replace both before 400,000km mark. Vehicle is on active trip â€” schedule on return from Bahir Dar.",
      priority: "high",
      due_date: "2026-05-30",
      status: "pending",
      created_date: "2026-05-15T16:00:00.000Z",
    },
    {
      id: "rec-005",
      vehicle_id: "veh-004",
      mechanic_name: "Sisay Tadesse",
      recommendations:
        "RR tire RR-4001 at 45% wear. Monitor on Jimma return trip-009. Replace at next service if below 35% on arrival.",
      priority: "medium",
      due_date: "2026-06-05",
      status: "pending",
      created_date: "2026-05-22T15:00:00.000Z",
    },
    {
      id: "rec-006",
      vehicle_id: "veh-001",
      mechanic_name: "Sisay Tadesse",
      recommendations:
        "Rear tires RL-1001 and RR-1001 both showing wear above 40%. Schedule replacement within the next 5,000km. Engine oil due in 600km â€” do not delay past current trip.",
      priority: "medium",
      due_date: "2026-06-01",
      status: "pending",
      created_date: "2026-05-10T17:00:00.000Z",
    },
  ],
};

const attachFallbackMedia = () => {
  seedData.Vehicle.forEach((vehicle) => {
    if (!Array.isArray(vehicle.photo_gallery) || vehicle.photo_gallery.length === 0) {
      vehicle.photo_gallery = [
        {
          id: `${vehicle.id}-photo-1`,
          name: `${vehicle.plate_number}.png`,
          type: "image/svg+xml",
          url: makePreviewDataUrl({
            title: vehicle.plate_number,
            subtitle: `${vehicle.make} ${vehicle.model}`,
            seed: vehicle.id,
          }),
        },
      ];
    }

    if (!Array.isArray(vehicle.contract_document)) {
      vehicle.contract_document = [];
    }
  });

  seedData.Driver.forEach((driver) => {
    if (!Array.isArray(driver.profile_photo) || driver.profile_photo.length === 0) {
      driver.profile_photo = [
        {
          id: `${driver.id}-profile-1`,
          name: `${driver.name}.png`,
          type: "image/svg+xml",
          url: makePreviewDataUrl({
            title: driver.name,
            subtitle: "Driver",
            seed: driver.id,
          }),
        },
      ];
    }

    if (!Array.isArray(driver.fayda_id_photos)) driver.fayda_id_photos = [];
    if (!Array.isArray(driver.normal_id_photos)) driver.normal_id_photos = [];
    if (!Array.isArray(driver.wastena_documents)) driver.wastena_documents = [];
    if (!Array.isArray(driver.contract_document)) driver.contract_document = [];
  });

  seedData.Trip.forEach((trip) => {
    if (!Array.isArray(trip.evidence_photos)) trip.evidence_photos = [];
  });

  seedData.ServiceSession.forEach((session) => {
    if (!Array.isArray(session.attachments)) session.attachments = [];
  });
};

attachFallbackMedia();

